export default function (){
  return ['jawbreaker',
  'buzzwords', 'transplant',
  'unworthy', 'nightclub',
  'nowadays', 'microwave',
  'awkward', 'flopping',
  'bikini', 'jackpot',
  'hello', 'cycle','addition','whistle','way',
  'weather','vessel','view',
  'violent','adjustment',
  'advertisement',
  'building','bulb','burn','burst','business','competition',
  'complete',
  'complex','condition',
  'connection','destruction',
  'detail',
  'development','different',
  'digestion',
  'direction','you',
  'young',
  'android',
  'transport',
  'tray',
  'tree',
  ]
}
